---
- name: Pull jenkins data volume image
  docker_image:
    name: calsaviour/jenkins_data

- name: Pull jenkins docker image
  docker_image:
    name: calsaviour/jenkins_docker

- name: Start jenkins image
  docker_container:
    name: centos7_test
    image: calsaviour/centos7_openjdk180
