---
- name: Prepare host environment with docker
  yum:
    name: docker-1.13.1


- name: Prepare host environment with docker-compose
  yum:
    name: docker-compose-1.9.0


- name: Make sure docker is running
  service:
    name: docker
    state: started

- name: Enable docker service
  docker:    
    state: enabled