---
- name: Prepare host environment with docker
  yum:
    name: docker-1.13.1
    notify:
      - start docker
      - enable docker



- name: Prepare host environment with docker-compose
  yum:
    name: docker-compose-1.9.0


  handlers:
    - name: start docker
      service:
        name: docker
        state: started

    - name: enable docker
      service:
        name: docker    
        enabled: yes
